#! /bin/bash

echo "Master Input The MRL you Want To download

"

read -p 'MRL : ' URL

echo "Master Tell Me The Quality You Want To Download The Video In

"

echo "e.g. 1080 720 480 360 240 144

"

read -p 'QUALITY : ' QUALITY

echo "Master Now Tell Me What You Want To Tag To The Name Of The Video

"

read -p 'TAG (A SINGLE WORD) : ' TAG

echo "Now Commencing Download

"

youtube-dl -f "bestvideo[height<=$QUALITY][ext=mp4][fps<=30]+bestaudio[ext=m4a]" --add-metadata --embed-thumbnail --newline -o "~/storage/shared/MY-MUSIC/%(title)s"[$TAG]".%(ext)s" "$URL"
