#! /data/data/com.termux/files/usr/bin/bash

echo "Master Input The MRL you Want To Download

"

read -p 'MRL : ' URL

echo "

Master Tell Me The File You Want To Cut And Download The Video In

"

youtube-dl -F $URL

echo "

"

read -p 'FILE CODE : ' QUALITY

echo "

Master Now Tell Me What You Want To Name The Video

"

echo "

And To Help You This Is The Original Video Name

"

youtube-dl --get-title $URL

read -p 'NAME: ' TAG

echo "Master Now Give Me The Start Time

"

read -p 'HH:MM:SS.MLS : ' STARTTIME

echo "Master Now Give Me The END Time

"

read -p 'HH:MM:SS.MLS : ' ENDTIME

echo "

Now Commencing Download

"

video=$(youtube-dl -g -f $QUALITY $URL)

filename="$TAG"

ffmpeg -i $video -ss $STARTTIME -to $ENDTIME  rename-me.mkv

mv rename-me.mkv ~/storage/shared/MY-MUSIC/"$filename.mkv"
