#! /data/data/com.termux/files/usr/bin/bash

cd && rm -rf MY-MUSIC && pkg install git -y && git clone https://github.com/animegamer4422/MY-MUSIC && cd MY-MUSIC && chmod +x my-musicinst && termux-setup-storage && bash my-musicinst
